name = "FinalProject"
uuid = "95bd645e-af01-4ede-b28e-ca08b1299139"
authors = ["jajoshi19 <jajoshi19@gmail.com>"]
version = "0.1.0"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SqpSolver = "ffdd34ce-459d-4fc7-82a1-202b2ab8becf"
TrajectoryGamesBase = "ac1ac542-73eb-4349-ae1b-660ab3609574"

[compat]
LinearAlgebra = "1.11.0"
SqpSolver = "0.1.0"
TrajectoryGamesBase = "0.3.11"
